name = "cf-nginx"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "43.218.77.16:1443"
UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
