name = "cf-nginx"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "43.218.77.16:1443"
UUID = "d13fc2f5-3e05-4795-81eb-44143a09e552"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
